workflows:
  desktop:
    name: Unity Desktop Workflow
    environment:
      groups:
        - unity # <-- (Includes UNITY_SERIAL, UNITY_USERNAME, UNITY_PASSWORD)
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
    scripts:
      - name: Activate License
        script: $UNITY_BIN -batchmode -quit -serial ${UNITY_SERIAL?} -username ${UNITY_USERNAME?} -password ${UNITY_PASSWORD?}
      - name: Build
        script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScripts.Build_Desktop -nographics
    artifacts:
      - "desktop"
    publishing:
      scripts:
        - name: Deactivate License
          script: $UNITY_BIN -batchmode -quit -returnlicense -nographics
  
  android-apk:
    name: Unity Android APK Workflow
    environment:
      groups:
        - unity # <-- (Includes UNITY_SERIAL, UNITY_USERNAME, UNITY_PASSWORD)
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
    scripts:
      - name: Activate License
        script: $UNITY_BIN -batchmode -quit -logFile -serial ${UNITY_SERIAL?} -username ${UNITY_USERNAME?} -password ${UNITY_PASSWORD?}
      - name: Build
        script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScripts.Build_Android -nographics
    artifacts:
      - app/build/outputs/**/**/*.apk
      - "android"
    publishing:
      scripts:
        - name: Deactivate License
          script: $UNITY_BIN -batchmode -quit -returnlicense -nographics
  
  android-ipa:
    name: Unity Android IPA Workflow
    environment:
      groups:
        - unity 
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
    scripts:
      - name: Activate License
        script: $UNITY_BIN -batchmode -quit -logFile -serial ${UNITY_SERIAL?} -username ${UNITY_USERNAME?} -password ${UNITY_PASSWORD?}
      - name: Build
        script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScripts.Build_Android_Bundle -nographics
    artifacts:
      - build/**/outputs/bundle/**/*.aab
      - "android"
    publishing:
      scripts:
        - name: Deactivate License
          script: $UNITY_BIN -batchmode -quit -returnlicense -nographics
          
  mac:
    name: Unity Mac Workflow
    environment:
      groups:
        - unity
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
    scripts:
      - name: Activate License
        script: $UNITY_BIN -batchmode -quit -logFile -serial ${UNITY_SERIAL?} -username ${UNITY_USERNAME?} -password ${UNITY_PASSWORD?}
      - name: Build
        script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScripts.Build_Mac -nographics
    artifacts:
      - "mac/CountMasterTesting.app"
    publishing:
      scripts:
        - name: Deactivate License
          script: $UNITY_BIN -batchmode -quit -returnlicense -nographics
          
  ios:
    name: Unity IOS Workflow
    environment:
      groups:
        - unity
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
    scripts:
      - name: Activate License
        script: $UNITY_BIN -batchmode -quit -logFile -serial ${UNITY_SERIAL?} -username ${UNITY_USERNAME?} -password ${UNITY_PASSWORD?}
      - name: Build
        script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScripts.Build_iOS_Development -nographics
    artifacts:
      - "mac/CountMasterTesting.app"
    publishing:
      scripts:
        - name: Deactivate License
          script: $UNITY_BIN -batchmode -quit -returnlicense -nographics