workflows:
  TestIntegration:
    name: Unity TestIntegration Workflow
    environment:
      groups:
        - unity # <-- (Includes UNITY_SERIAL, UNITY_USERNAME, UNITY_PASSWORD)
        - ssh
        - git
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
    scripts:
      - name: Activate License
        script: $UNITY_BIN -batchmode -quit -serial ${UNITY_SERIAL?} -username ${UNITY_USERNAME?} -password ${UNITY_PASSWORD?}
      - name: Gather Dependencies
        script: sh BuildScripts/GatherDependencies.sh
      - name: Build
        script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScripts.Build_Desktop -nographics
    artifacts:
      - "desktopBuild"
    publishing:
      scripts:
        - name: Deactivate License
          script: $UNITY_BIN -batchmode -quit -returnlicense -nographics
  
  desktop:
    name: Unity Desktop Workflow
    environment:
      groups:
        - unity # <-- (Includes UNITY_SERIAL, UNITY_USERNAME, UNITY_PASSWORD)
        - ssh
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
    scripts:
      - name: Activate License
        script: $UNITY_BIN -batchmode -quit -serial ${UNITY_SERIAL?} -username ${UNITY_USERNAME?} -password ${UNITY_PASSWORD?}
      - name: Build
        script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScripts.Build_Desktop -nographics
    artifacts:
      - "desktopBuild"
    publishing:
      scripts:
        - name: Deactivate License
          script: $UNITY_BIN -batchmode -quit -returnlicense -nographics
  
  android-ipa:
    name: Unity Android IPA Workflow
    environment:
      groups:
        - unity
        - keystore_credentials
        - google_play
        - ssh
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
        PACKAGE_NAME: <PACKAGE_NAME>
    scripts:
      - name: Activate License
        script: $UNITY_BIN -batchmode -quit -logFile -serial ${UNITY_SERIAL?} -username ${UNITY_USERNAME?} -password ${UNITY_PASSWORD?} 
      - name: Build
        script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScripts.Build_Android_Bundle -nographics
    artifacts:
      - androidBuild/*.aab
      - "androidBuild"
    publishing:
      scripts:
        - name: Deactivate Unity License
          script: $UNITY_BIN -batchmode -quit -returnlicense -nographics
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: alpha
        
  android-apk:
    name: Unity Android APK Workflow
    environment:
      groups:
        - unity
        - keystore_credentials
        - ssh
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
        PACKAGE_NAME: <PACKAGE_NAME>
    scripts:
      - name: Activate License
        script: $UNITY_BIN -batchmode -quit -logFile -serial ${UNITY_SERIAL?} -username ${UNITY_USERNAME?} -password ${UNITY_PASSWORD?}   
      - name: Build
        script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScripts.Build_Android -nographics
    artifacts:
      - androidBuild/*.apk
      - "androidBuild"
    publishing:
      scripts:
        - name: Deactivate Unity License
          script: $UNITY_BIN -batchmode -quit -returnlicense -nographics
  
  mac:
    name: Unity Mac Workflow
    environment:
      groups:
        - unity
        - ssh
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
    scripts:
      - name: Activate License
        script: $UNITY_BIN -batchmode -quit -logFile -serial ${UNITY_SERIAL?} -username ${UNITY_USERNAME?} -password ${UNITY_PASSWORD?}
      - name: Build
        script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScripts.Build_Mac -nographics
    artifacts:
      - "macBuild/CountMasterTesting.app"
    publishing:
      scripts:
        - name: Deactivate License
          script: $UNITY_BIN -batchmode -quit -returnlicense -nographics
          
  ios:
    name: Unity IOS Workflow
    environment:
      groups:
        - unity
        - ssh
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
    scripts:
      - name: Activate License
        script: $UNITY_BIN -batchmode -quit -logFile -serial ${UNITY_SERIAL?} -username ${UNITY_USERNAME?} -password ${UNITY_PASSWORD?}
      - name: Build
        script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScripts.Build_iOS_Development -nographics
    artifacts:
      - "macBuild/CountMasterTesting.app"
    publishing:
      scripts:
        - name: Deactivate License
          script: $UNITY_BIN -batchmode -quit -returnlicense -nographics