workflows:
  desktop:
    name: Desktop Workflow
    environment:
      groups:
        - unity
        - git
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
    scripts:
      - &activate_license
        name: Activate License
        script: $UNITY_BIN -batchmode -quit -serial ${UNITY_SERIAL?} -username ${UNITY_USERNAME?} -password ${UNITY_PASSWORD?}
      - &gather_dependencies
        name: Gather Dependencies
        script: sh BuildScripts/PrepareCodeMagicBuild.sh
      - &build_desktop
        name: Build
        script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScripts.Build_Desktop -nographics
    artifacts:
      - "desktopBuild"
    publishing:
      scripts:
        - &deactivate_license
          name: Deactivate License
          script: $UNITY_BIN -batchmode -quit -returnlicense -nographics
  
  android-ipa-no-publishing:
    name: Android IPA No Publishing Workflow
    environment:
      groups:
        - unity
        - keystore_credentials
        - google_play
        - git
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
        PACKAGE_NAME: com.NikigmiStudios.CountMaster
    scripts:
      - *activate_license
      - *gather_dependencies 
      - &set_build_number_and_build_ipa
        name: Set build number and export Unity
        script: |
          export NEW_BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks=alpha) + 1))
          $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScript.Build_Android_Bundle -nographics
    artifacts:
      - androidBuild/*.aab
      - "androidBuild"
    publishing:
      scripts:
        - *deactivate_license
  
  android-ipa-internal:
    name: Android IPA Internal Testing Workflow
    environment:
      groups:
        - unity
        - keystore_credentials
        - google_play
        - git
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
        PACKAGE_NAME: com.NikigmiStudios.CountMaster
    scripts:
      - *activate_license
      - *gather_dependencies 
      - *set_build_number_and_build_ipa
    artifacts:
      - androidBuild/*.aab
      - "androidBuild"
    publishing:
      scripts:
        - *deactivate_license
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
  
  android-ipa-alpha:
    name: Android IPA Closed Testing Workflow
    environment:
      groups:
        - unity
        - keystore_credentials
        - google_play
        - git
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
        PACKAGE_NAME: com.NikigmiStudios.CountMaster
    scripts:
      - *activate_license
      - *gather_dependencies 
      - *set_build_number_and_build_ipa
    artifacts:
      - androidBuild/*.aab
      - "androidBuild"
    publishing:
      scripts:
        - *deactivate_license
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: alpha
        submit_as_draft: true
        
  android-ipa-beta:
    name: Android IPA Open Testing Workflow
    environment:
      groups:
        - unity
        - keystore_credentials
        - google_play
        - git
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
        PACKAGE_NAME: com.NikigmiStudios.CountMaster
    scripts:
      - *activate_license
      - *gather_dependencies 
      - *set_build_number_and_build_ipa
    artifacts:
      - androidBuild/*.aab
      - "androidBuild"
    publishing:
      scripts:
        - *deactivate_license
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: beta
        submit_as_draft: true
        
  android-ipa-production:
    name: Android IPA Production Workflow
    environment:
      groups:
        - unity
        - keystore_credentials
        - google_play
        - git
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
        PACKAGE_NAME: com.NikigmiStudios.CountMaster
    scripts:
      - *activate_license
      - *gather_dependencies 
      - *set_build_number_and_build_ipa
    artifacts:
      - androidBuild/*.aab
      - "androidBuild"
    publishing:
      scripts:
        - *deactivate_license
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: production
        submit_as_draft: true
        
  android-apk:
    name: Android APK Workflow
    environment:
      groups:
        - unity
        - keystore_credentials
        - git
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
        PACKAGE_NAME: com.NikigmiStudios.CountMaster
    scripts:
      - *activate_license
      - *gather_dependencies  
      - name: Build
        script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScripts.Build_Android -nographics
    artifacts:
      - androidBuild/*.apk
      - "androidBuild"
    publishing:
      scripts:
        - *deactivate_license
  
  mac:
    name: Mac Workflow
    environment:
      groups:
        - unity
        - git
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
    scripts:
      - *activate_license
      - *gather_dependencies 
      - name: Build
        script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScripts.Build_Mac -nographics
    artifacts:
      - "macBuild/CountMasterTesting.app"
    publishing:
      scripts:
        - *deactivate_license
          
  ios:
    name: IOS Workflow
    environment:
      groups:
        - unity
        - git
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
    scripts:
      - *activate_license
      - *gather_dependencies 
      - name: Build
        script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScripts.Build_iOS_Development -nographics
    artifacts:
      - "macBuild/CountMasterTesting.app"
    publishing:
      scripts:
        - *deactivate_license