workflows:
  common:
    name: Common Scripts Workflow
    environment:
      groups:
        - unity
        - git
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
    scripts:
      scripts:
      - &activate_license
        name: Activate License
        script: $UNITY_BIN -batchmode -quit -serial ${UNITY_SERIAL?} -username ${UNITY_USERNAME?} -password ${UNITY_PASSWORD?}
      - &gather_dependencies
        name: Gather Dependencies
        script: sh BuildScripts/PrepareCodeMagicBuild.sh
      - &deactivate_license
        name: Deactivate License
        script: $UNITY_BIN -batchmode -quit -returnlicense -nographics
        
  desktop:
    name: Unity Desktop Workflow
    environment:
      groups:
        - unity
        - git
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
    scripts:
      - *activate_license
      - *gather_dependencies
      - name: Build
        script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScripts.Build_Desktop -nographics
    artifacts:
      - "desktopBuild"
    publishing:
      scripts:
        - *deactivate_license
  
  android-ipa:
    name: Unity Android IPA Workflow
    environment:
      groups:
        - unity
        - keystore_credentials
        - google_play
        - git
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
        PACKAGE_NAME: <PACKAGE_NAME>
    scripts:
      - *activate_license
      - *gather_dependencies 
      - name: Build
        script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScripts.Build_Android_Bundle -nographics
    artifacts:
      - androidBuild/*.aab
      - "androidBuild"
    publishing:
      scripts:
        - *deactivate_license
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: alpha
        
  android-apk:
    name: Unity Android APK Workflow
    environment:
      groups:
        - unity
        - keystore_credentials
        - git
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
        PACKAGE_NAME: <PACKAGE_NAME>
    scripts:
      - *activate_license
      - *gather_dependencies  
      - name: Build
        script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScripts.Build_Android -nographics
    artifacts:
      - androidBuild/*.apk
      - "androidBuild"
    publishing:
      scripts:
        - *deactivate_license
  
  mac:
    name: Unity Mac Workflow
    environment:
      groups:
        - unity
        - git
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
    scripts:
      - *activate_license
      - *gather_dependencies 
      - name: Build
        script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScripts.Build_Mac -nographics
    artifacts:
      - "macBuild/CountMasterTesting.app"
    publishing:
      scripts:
        - *deactivate_license
          
  ios:
    name: Unity IOS Workflow
    environment:
      groups:
        - unity
        - git
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
    scripts:
      - *activate_license
      - *gather_dependencies 
      - name: Build
        script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScripts.Build_iOS_Development -nographics
    artifacts:
      - "macBuild/CountMasterTesting.app"
    publishing:
      scripts:
        - *deactivate_license